[package]
name = "rawthumb"
version = "0.1.0"
edition = "2024"
description = "Fast, extensible RAW thumbnail and preview extractor"

[dependencies]
thiserror = "2.0.17"
quickexif = "0.1"
anyhow = "1.0"
once_cell = "1.21"
tempfile = "3.24"
log = "0.4"
memchr = "2"
turbojpeg = { version = "1.3.3", default-features = false, features = ["cmake", "pkg-config"] }
image = { version = "0.25", default-features = false, features = ["jpeg"] }
fast_image_resize = { version = "5.4.0", features = ["image"] }
memmap2 = "0.9"
walkdir = "2.5"

[dev-dependencies]
env_logger = "0.11"
rayon = "1.11"
